@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTU4NzMyNDU1NCwiZXhwIjoxNTg3MzI4MTU0LCJuYmYiOjE1ODczMjQ1NTQsImp0aSI6InRhSzdWNXU1bExmdzY4MkgiLCJzdWIiOjQsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.BBqHMLJQiPwrxZDb_axwIujKFovSdct5seP7iUNiIhQ



POST http://localhost:8000/api/previewApiNameFromMerchantName
Content-Type: application/json
Accept: application/json

{
    "fullName": "dit-iseenmerchantapiname aaa"
}

###

POST http://localhost:8000/api/auth/registerMerchant
Content-Type: application/json
Accept: application/json

{
    "firstName": "Ditiseenvoornaam",
    "lastName": "Ditiseenachternaam",
    "email": "arnaud.verpoucke@hotmail.com",
    "password": "Arnaud_2019",
    "password_confirmation": "Arnaud_2019",
    "merchantName": "ditiseenmerchantapiname",
    "mobilePhone": "0400 123 456",
    "address_street": "Ergenslaan",
    "address_number": "22b",
    "address_zip": "8520",
    "address_city": "Kuurne",
    "tax_number": "BE 1234.567.890",
    "merchantPhone": "0479 333 222"
}


###

POST http://localhost:8000/api/auth/registerCustomer
Content-Type: application/json
Accept: application/json

{
    "firstName": "Arnaud",
    "lastName": "Verpoucke",
    "email": "arnaud.verpoucke@hotmail.com",
    "password": "Arnaud_2019",
    "password_confirmation": "Arnaud_2019",
    "mobilePhone": "0400 123 456",
    "acceptsTermsAndConditions": "true"
}


###

POST http://localhost:8000/admin/login
Content-Type: application/json

{
    "email": "arnaud.verpoucke@hotmail.com",
    "password": "Arnaud_2019"
}


###

POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "arnaud@test.com",
    "password": "123"
}

###


POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "emma@test.com",
    "password": "123"
}


###


POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "arnaud.verpoucke@hotmail.com",
    "password": "Arnaud_2019"
}


###


POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "arnaud@plenso.be",
    "password": "Bob_2019"
}

###

POST http://localhost:8000/api/placeOrder
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "merchantId": 1,
    "deliveryMethod": "takeaway",
    "addressStreet": "Vijfwegenstraat",
    "addressNumber": 200,
    "addressZipCode": 8800,
    "addressCity": "Roeselare",
    "productIds": ["1","2","3"],
    "requestedTime": "22:30"
}

###

POST http://localhost:8000/sendContactForm
Content-Type: application/json
Accept: application/json

{
    "fullName": "Arnaud Verpoucke",
    "email": "arnaud.verpoucke@hotmail.com",
    "message": "Hallo dit is een test. Bla Bla Bla. \n Testregel."
}

###


GET http://localhost:8000/api/test/merchant-protected
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

POST http://localhost:8000/api/auth/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


###

GET http://localhost:8000/api/merchant/1
Accept: application/json

###


POST http://localhost:8000/api/merchant/addProduct
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "French fries",
    "price": "2,80",
    "available": true
}

###

GET http://localhost:8000/api/merchant/all
Accept: application/json
