@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTU4NDU2NTgxOCwiZXhwIjoxNTg0NTY5NDE4LCJuYmYiOjE1ODQ1NjU4MTgsImp0aSI6Ik90OUdnTE03WVA1U1lwekwiLCJzdWIiOjMsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.CJM4BKTKytdGSObH-tIjzgHwknb1yzUdKrhtUC4geN8

POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "arnaud@test.com",
    "password": "123"
}

###


POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "emma@test.com",
    "password": "123"
}

###

POST http://localhost:8000/api/placeOrder
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "merchantId": 1,
    "deliveryMethod": "delivery",
    "addressStreet": "Vijfwegenstraat",
    "addressNumber": 200,
    "addressZipCode": 8800,
    "addressCity": "Roeselare",
    "productIds": [1,2,3],
    "requestedTime": "{{$datetime 'YYYY-MM-DD H:m:s' 2 h}}"
}

###

GET http://localhost:8000/api/test/merchant-protected
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

POST http://localhost:8000/api/auth/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


